# Generated by Django 5.0 on 2024-01-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_photo',
            field=models.ImageField(default='', upload_to='covers'),
        ),
    ]
