# Generated by Django 5.0 on 2024-01-11 14:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug_title',
            field=autoslug.fields.AutoSlugField(max_length=200, unique=True, verbose_name='Course Slug'),
        ),
    ]
