# Generated by Django 5.0 on 2024-01-16 16:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_slug_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug_title',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='title', unique=True, verbose_name='Course Slug'),
        ),
    ]
